
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dim_model'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring seeds
# Full documentation: https://docs.getdbt.com/reference/seed-configs
seeds:

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  data_vault:
    staging:
      +materialized: view
      +database: "sandbox"
      +schema: "stage"
    intermediate:
      +materialized: table
      +database: "sandbox"
      +schema: "intermediate"
    marts:
      +materialized: table
      +database: "sandbox"
      +schema: "data_mart"
  dbt_project_evaluator:
    +database: "sandbox"
    +schema: "dbt_project_evaluator"

dispatch:
  - macro_namespace: dbt
    search_order: ['dbt_project_evaluator', 'dbt']

vars:
  dbt_project_evaluator:
    # set doc and test coverage percentage
    documentation_coverage_target: 75
    test_coverage_target: 75
    # set constraints tests as primary key test
    primary_key_test_macros: [["dbt.test_unique", "dbt.test_not_null"],["dbt_constraints.test_primary_key"]]
    # set model types
    marts_folder_name: 'marts'
    marts_prefixes: ['dim_', 'fct_']
    # set model fanout threshold
    models_fanout_threshold: 5
    # exclude packages
    exclude_packages: ["dbt_artifacts", "dbt_project_evaluator"]
    exclude_paths_from_project: ["/date_spine.sql"]
